

server:
  port: 8090
  servlet:
    context-path: /api/v1

spring:
  application:
    name: patient-app
  profiles:
    active: local
  cloud:
    config:
      label: ${spring.profiles.active}
      uri: http://localhost:8888
      profile: ${spring.profiles.active}
      fail-fast: false
      enabled: true
    vault:
      enabled: false
      uri: http://127.0.0.1:8200
      token: hvs.yVo6q9PbPusB7fZUAYKFOnLb
      kv:
        enabled: true
      backend: secret
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        instance-id: ${spring.application.name}-${random.value}
        health-check-interval: 10s
        health-check-path: /actuator/health
  config:
    import: "configserver:"
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest




app:
  user:
    url: /api/v1
  rabbitmq:
    exchange: patient-exchange
    routing-key: patient.created
    queue: patient-queue