

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local
    username: root
    password: mysql
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000ms
      database: 0

