# yaml-language-server: $schema=https://json.schemastore.org/spring-boot-configuration-metadata.json


spring:
  application:
    name: user-role
  profiles:
    active: local
  cloud:
    config:
      label: ${spring.profiles.active}
      uri: http://localhost:8888
      profile: ${spring.profiles.active}
  config:
    import: "configserver:"

server:
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: "*"






