# yaml-language-server: $schema=https://json.schemastore.org/spring-boot-configuration-metadata.json


spring:
  application:
    name: user-role
  profiles:
    active: local
  cloud:
    vault:
      enabled: true
      uri: http://127.0.0.1:8200
      token: ${VAULT.TOKEN}
      kv:
        enabled: true
      backend: secret
    config:
      label: ${spring.profiles.active}
      uri: http://localhost:8888
      profile: ${spring.profiles.active}
      fail-fast: false
      enabled: true
  config:
    import: "vault://,configserver:"
server:
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.vault: DEBUG
    org.springframework.vault: DEBUG




