# yaml-language-server: $schema=https://json.schemastore.org/spring-boot-configuration-metadata.json


spring:
  application:
    name: user-role
  profiles:
    active: prod
  cloud:
    vault:
      enabled: false
      uri: http://127.0.0.1:8200
      token: hvs.yVo6q9PbPusB7fZUAYKFOnLb
      kv:
        enabled: true
      backend: secret
    config:
      label: ${spring.profiles.active}
      uri: http://localhost:8888
      profile: ${spring.profiles.active}
      fail-fast: false
      enabled: true
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
  config:
    import: "configserver:"
server:
  port: 8080
  servlet:
    context-path: /api/v1
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.vault: DEBUG




